title: "Chanezon on AI"
logo: /assets/img/logo.png
description: "Patrick Chanezon on AI, software development, cloud, containers and developer relations"
show_downloads: false
theme: jekyll-theme-minimal
   
